#!/usr/bin/with-contenv bash

if [ ! -d /swag ]; then
  echo "SWAG appdata is not mounted to /swag, this image is intended to be used with SWAG and startup errors will occur if its appdata not mounted."
  echo "Please re-start the container with SWAG appdata mounted to /swag"
  sleep infinity
fi

# make our folders
mkdir -p \
  /config/{nginx/site-confs,nginx/proxy-confs,public_html,log/nginx} \
  /run \
  /var/lib/nginx/tmp/client_body \
  /var/tmp/nginx

# copy config files
[[ ! -f /config/nginx/nginx.conf ]] &&
  cp /defaults/nginx.conf /config/nginx/nginx.conf
[[ ! -f /config/nginx/site-confs/default.conf ]] &&
  cp /defaults/default.conf /config/nginx/site-confs/default.conf
[[ $(find /config/public_html -type f | wc -l) -eq 0 ]] &&
  cp /defaults/index.html /config/public_html/index.html

# setup symlinks
[[ ! -d /config/keys ]] &&
  ln -s /swag/keys /config/keys
[[ ! -f /config/nginx/ssl.conf ]] &&
  ln -s /swag/nginx/ssl.conf /config/nginx/ssl.conf
[[ ! -f /config/nginx/security.conf ]] &&
  ln -s /swag/nginx/security.conf /config/nginx/security.conf
[[ ! -f /config/nginx/cloudflare.conf ]] &&
  ln -s /swag/nginx/cloudflare.conf /config/nginx/cloudflare.conf
[[ ! -f /config/nginx/dhparams.pem ]] &&
  ln -s /swag/nginx/dhparams.pem /config/nginx/dhparams.pem
[[ ! -f /config/nginx/proxy.conf ]] &&
  ln -s /swag/nginx/proxy.conf /config/nginx/proxy.conf

cp -f /swag/nginx/site-confs/* /config/nginx/site-confs/ >/dev/null 2>&1

sed -i \
  -e 's/root .*;/root \/config\/public_html\/;/g' \
  -e 's/index .*;/index index.html;/g' \
  /config/nginx/site-confs/*

# permissions
chown -R abc:abc \
  /config \
  /var/lib/nginx \
  /var/tmp/nginx
chmod -R g+w \
  /config/{nginx,public_html}
chmod -R 644 /etc/logrotate.d

if ! nginx -t -c /config/nginx/nginx.conf &>/dev/null; then
  nginx -t -c /config/nginx/nginx.conf
  echo "[cont-init.d] 20-config: Nginx config is invalid, Check your configs!"
  sleep infinity
fi
