#!/usr/bin/with-contenv bash

if [ ! -d /swag ]; then
  echo "SWAG appdata is not mounted to /swag, this image is intended to be used with SWAG and startup errors will occur if its appdata not mounted."
  echo "Please re-start the container with SWAG appdata mounted to /swag"
  sleep infinity
fi

# make our folders
mkdir -p \
  /config/{nginx/site-confs,nginx/proxy-confs,public_html,log/nginx,keys} \
  /run \
  /var/lib/nginx/tmp/client_body \
  /var/tmp/nginx

# copy config files
[[ ! -f /config/nginx/nginx.conf ]] &&
  cp /defaults/nginx.conf /config/nginx/nginx.conf
[[ ! -f /config/nginx/site-confs/default.conf ]] &&
  cp /defaults/default.conf /config/nginx/site-confs/default.conf
[[ $(find /config/public_html -type f | wc -l) -eq 0 ]] &&
  cp /defaults/index.html /config/public_html/index.html

# permissions
chown -R abc:abc \
  /config \
  /var/lib/nginx \
  /var/tmp/nginx
chmod -R g+w \
  /config/{nginx,public_html}
chmod -R 644 /etc/logrotate.d
