#!/usr/bin/with-contenv bash

if [ ! -d /swag ]; then
	echo "Maintenance will start in standalone mode as no SWAG appdata is mounted to /swag"
fi

# make our folders
mkdir -p \
	/config/{nginx/site-confs,nginx/proxy-confs,www,log/nginx} \
	/run \
	/var/lib/nginx/tmp/client_body \
	/var/tmp/nginx

# cleanup logs
find /config/log -name "*.log" -delete

# copy config files
[[ ! -f /config/nginx/nginx.conf ]] &&
	cp /defaults/nginx.conf /config/nginx/nginx.conf
[[ ! -f /config/nginx/site-confs/default ]] &&
	cp /defaults/default /config/nginx/site-confs/default
if ! ls -1qA /config/www/ | grep -q .; then
	cp /defaults/index.html /config/www/index.html
fi

if [ -d /swag ]; then
	if [ ! -f /config/includes.txt ]; then
		printf "proxy.conf\nssl.conf\ndhparams.pem" >/config/includes.txt
		echo "Add a list of files in the /config/includes.txt file to migrate over from SWAG. Relative to the Nginx folder within the appdata folder. i.e. use sample.conf instead of /config/nginx/sample.conf.
This is useful if you have any includes in your Nginx configs but also works for any folder/file within the Nginx folder.
This only works for files within the nginx directory!
Restart the container when you are done"
		sleep infinity
	fi
fi
